[build]
# Configure getrandom to use the js backend
rustflags = ["--cfg=getrandom_js"]

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

# Optimize for size in release mode
[profile.release]
opt-level = "s"
lto = true
codegen-units = 1